---
- name: set fact allow_downgrade to no
  set_fact: allow_downgrade=no

- name: set fact allow_downgrade to yes
  set_fact: allow_downgrade=yes
  when: es_allow_downgrades

- name: Ensure libselinux-python on CentOS 6.x
  become: yes
  shell: yum -y install libselinux-python warn=false
  when: ( ansible_distribution == "CentOS" ) and ( ansible_distribution_major_version == "6" )

- name: RedHat - add Elasticsearch repo
  become: yes
  template:
    src: 'elasticsearch.repo'
    dest: '/etc/yum.repos.d/elasticsearch-{{ es_repo_name }}.repo'
  when: es_use_repository and es_add_repository and deployment_environment_id == 'local_development'

- name: RedHat - remove unused Elasticsearch repo
  become: yes
  file:
    path: '/etc/yum.repos.d/elasticsearch-{{ es_other_repo_name }}.repo'
    state: absent
  when: es_use_repository

- name: RedHat - include versionlock
  include: elasticsearch-RedHat-version-lock.yml

- name: RedHat - Remove elasticsearch if major version changes
  block:
  - name: remove package
    shell: 'yum remove -y {{ es_package_name }} warn=false'
  - name: delete old configurations
    file: 
      path: /etc/elasticsearch
      state: absent
  - name: delete old configurations
    file: 
      path: /var/lib/elasticsearch
      state: absent
  - name: delete old configurations
    file: 
      path: /usr/share/elasticsearch
      state: absent
  become: yes
  when: es_major_version_changed

- name: RedHat - Remove the other elasticsearch package if switching between OSS and standard
  become: yes
  shell: 'yum remove -y {{ es_other_package_name }} warn=false'

- name: Include optional user and group creation.
  when: (es_user_id is defined) and (es_group_id is defined)
  include: elasticsearch-optional-user.yml

- name: RedHat - Install Elasticsearch
  become: yes
  shell: 'yum -y install {{ es_package_name }}{% if es_version is defined and es_version != ""  %}-{{ es_version }}{% endif %} warn=false'
  when: es_use_repository
  register: redhat_elasticsearch_install_from_repo
  notify: restart elasticsearch
  until: redhat_elasticsearch_install_from_repo.rc == 0
  retries: 5
  delay: 10
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"

- name: RedHat - Check if elasticsearch is installed
  shell: "yum info elasticsearch-{{ es_version }} warn=false"
  register: es_info
  ignore_errors: true

- name: RedHat - Install Elasticsearch from url
  become: yes
  shell: 'yum -y install {% if es_custom_package_url is defined %}{{ es_custom_package_url }}{% else %}{{ es_package_url }}-{{ es_version }}.noarch.rpm{% endif %} warn=false'
  when:
    - not es_use_repository
    - es_info.rc > 0
  register: elasticsearch_install_from_package
  notify: restart elasticsearch
